### PR TITLE
docs(terminology): impl

### PR DESCRIPTION
**Pull request by ArhanCodes**

### CODE REVIEW

**Comment by twisttaan** [comment]
This creates confusion for people new to creating bots on the platform (Discord).

**Comment by twisttaan** [comment]
Maybe we should link "HTTP Discord bots" to another page that describes all the "Discord developer buzz words".

**Review by twisttaan — CHANGES_REQUESTED** [review]
Link "HTTP Discord bots" to another page that describes all the "Discord developer buzzwords".

**Comment by ArhanCodes** [comment]
Yes, but it also might create confusion for people who think that Disploy is a framework for building Discord bots instead of HTTP Discord bots.

**Comment by twisttaan** [comment]
> Yes, but it also might create confusion for people who think that Disploy is a framework for building Discord bots instead of HTTP Discord bots.

Websocket Discord bots and HTTP Discord bots both fall under the term "Discord bots".

**Comment by megatank58** [comment]
Personally i agree with the OP here, this can create confusion for advanced users, perhaps the phrase "Discord bots with HTTP requests" is better?

**Pull request closed without merging**
